version: "3.8"
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - nextjs_cache:/app/.next
      - .:/app
    command: npm run dev
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development

volumes:
  nextjs_cache:
